sudo: false
dist: focal
os: linux

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

language: go
go:
  - "1.15"

# Only clone the most recent commit.
git:
  depth: 1

install:
  - "go get -u -v github.com/kevinburke/go-bindata/..."

jobs:
  include:
    - name: analyse
      script:
      - make check-formatting
      - make vet
      arch: amd64
    - name: build docker images
      script:
      - make image
      arch: amd64

script: 
  - make magneticod
  - make magneticow