sudo: false
dist: focal
os: linux

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

language: go
go:
  - "1.15"

# Only clone the most recent commit.
git:
  depth: 1

before_install:
  # Dump environment variables
  - printenv

install:
  - "go get -u -v github.com/kevinburke/go-bindata/..."

before_script:
  - "make magneticod"
  - "make magneticow"
  - "make image"

jobs:
  include:
    - stage: analyse
      name: format
      script: make check-formatting
    - name: analyse
      script: make vet
    - stage: test
      script: make test
    - stage: build
      name: "magneticod"
      script: make magneticod
    - script: make magneticow
      name: "magneticow"
    - script: make image
      name: "docker image"
  exclude:
    - arch:
      - arm64
      - ppc64le
      - s390x
      name: format
    - arch:
      - arm64
      - ppc64le
      - s390x
      name: analyse
    - arch:
      - arm64
      - ppc64le
      - s390x
      name: "docker image"
