sudo: false
dist: focal
os: linux

language: go
go:
  - "1.15"

# Only clone the most recent commit.
git:
  depth: 1

before_install:
  # Dump environment variables
  - printenv

install:
  - "go get -u -v github.com/kevinburke/go-bindata/..."

before_script:
  - "make magneticod"
  - "make magneticow"
  - "make image"

jobs:
  include:
    - stage: analyse
      # only run analysis on amd64
      arch:
      - amd64
      name: format
      script: make check-formatting
    - name: analyse
      # only run analysis on amd64
      arch:
        - amd64
      script: make vet
    - stage: test
      script: make test
      arch:
        - amd64
        - arm64
        - ppc64le
        - s390x
    - stage: build
      name: "magneticod"
      arch:
      - amd64
      - arm64
      - ppc64le
      - s390x
      script: make magneticod
    - script: make magneticow
      arch:
        - amd64
        - arm64
        - ppc64le
        - s390x
      name: "magneticow"
    - script: make image
      arch:
        - amd64
      name: "docker image"
    # - name: deploy
    #   if: branch = master
