sudo: false
dist: focal
os: linux

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

language: go
go:
  - "1.15"

# Only clone the most recent commit.
git:
  depth: 1

install:
  - "go get -u -v github.com/kevinburke/go-bindata/..."

jobs:
  include:
    - stage: analyse
      name: check-formatting
      script:
      - make check-formatting
      arch: amd64
    - stage: analyse
      name: static analyses
      script:
      - make vet
      arch: amd64
    - stage: build
      name: build magneticow
      script:
      - make magneticow
    - stage: build
      name: build magneticod
      script:
      - make magneticod
    - stage: build
      name: build docker images
      script:
      - make image
      arch: amd64